name: CI

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Format
        run: pnpm format:check

      - name: Check types
        run: pnpm check-types

      - name: Build App
        run: pnpm build
        env:
          MINIFY: "true"

      - name: Install Playwright browsers
        run: pnpm playwright:install

      - name: E2E tests (Playwright)
        run: pnpm e2e
        env:
          CI: "true"
